version: '3.7'
services:
  calculator-app:
    container_name: calculator-app
    hostname: calculator-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '8080:8080'
    volumes:
      - ./:/calculator-app
    entrypoint: npm
    command: 'run start:ts:watch'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    networks:
      - calculator-network

networks:
  calculator-network:
    external: true
